### ISSUE TITLE
i can't spawn any objects.

### ISSUE THREAD

**Issue by Letspatrick** [kibook/redm-object-spooner#1]
i can't spawn any objects.

I wrote all rights in the Server.cfg.

**Comment by kibook** [comment]
Hello! Is this a first-time install, or did you have the spooner working before? Recently the spawn control was changed to the E key by default instead of left-click, so if you used the spooner prior to that you may just be hitting the wrong button.

If this is the first time you've installed the spooner, could you please include what you added to your server.cfg? Thanks!

**Comment by Letspatrick** [comment]
I'm very sorry, I totally missed it. Now it goes ... Thanks for the great work, your scripts and for sharing them here. thanks man! Greetings from Germany!

**Comment by kibook** [comment]
No problem, glad you got it working! 😄
